name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "2.x"

      - name: Cache dependencies
        run: deno cache --reload --lock=deno.lock main.ts cli/cli.ts examples/client.ts

      - name: Run tests
        run: deno test --allow-net --allow-env --allow-read
